#!/bin/bash

# list of global variables that hold default values when installing arch

PS3='Enter option: '
NETWORK_DEVICE=''
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"

# EDITOR {{{
EDITOR='vim'
# }}}
# MIRRORLIST {{{
MIRRORLIST='sort by download speed'
# }}}
# PARTITION {{{
DEVICE='/dev/sda'

BOOT_PARTITION=''
ROOT_PARTITION=''
HOME_PARTITION=''
SWAP_PARTITION=''

FORMAT_BOOT_PARTITION=0
FORMAT_HOME_PARTITION=0

MOUNTPOINT='/mnt'
# }}}
# LOCALE {{{
LOCALE='en_US'
# }}}
# TIMEZONE {{{
ZONE='Asia'
SUBZONE='Ho_Chi_Minh'
# }}}
# HARDWARE CLOCK {{{
HARDWARE_CLOCK='UTC'
# }}}
# KEYMAP {{{
KEYMAP='us'
# }}}
# HOSTNAME {{{
HOSTNAME='nearPC'
# }}}
# USERNAME {{{
USERNAME=''
# }}}
# DESKTOP ENVIRONMENT {{{
DESKTOP_ENVIRONMENT='KDE'
# }}}
# DOTFILES {{{
DOTFILES='NearHuscarl dotfiles'
# }}}
